### ISSUE TITLE
Some functions require numpy > 1.19.0

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/GeoUtils#207]
**Describe the bug**
The comparison between two raster, using the overload `__eq__` does not work with numpy < 1.19.

**To Reproduce**
Use numpy < 1.19, then
```
import geoutils.georaster as gr
from geoutils import datasets
r = gr.Raster(datasets.get_path("landsat_B4"))
r == r
```
raises the error:

> TypeError: _array_equal_dispatcher() got an unexpected keyword argument 'equal_nan'

**Expected behavior**
This should not raise an error.
To avoid this, either find an alternative to 'equal_nan' or specify the numpy version needed in the requirements.

**System (please complete the following information):**
numpy version '1.18.1'

**Comment by erikmannerfelt** [comment]
Nice that you found out! I'm sure there's a way around it. Worst case, we can just go back to `np.nansum(np.abs(r - r2)) < *dtype_min*`

**Comment by erikmannerfelt** [comment]
Actually, it seems it's just possible to compare with zero:
```python
>>> np.float32(0.11111111111) - np.float32(0.111111111111111111111111111111)
0.0
```

So it should be as simple as `np.nansum(np.abs(r - r2)) == 0.0`. I wonder what happens with masks though...
